<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AboutTheGame.aspx.cs" Inherits="AboutTheGame" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<center>
<div class="AboutTheGameMainDiv">
<div id="div1">Rocket League</div>
<div id="AboutTheGameDiv1">Rocket League is a vehicular soccer video game developed and published by Psyonix. The game was first released for Microsoft Windows and PlayStation 4 in July 2015, with ports for Xbox One, OS X, and Linux being released in 2016. 505 Games began distributing a physical retail version for PlayStation 4 and Xbox One in June 2016.
Described as "soccer, but with rocket-powered cars", Rocket League has one to four players assigned to each of the two teams, using rocket-powered vehicles to push a ball into their opponent's goal and score points over the course of a match. The game includes single-player and multiplayer modes which can be played both locally and online, including cross-platform play between the PlayStation 4 and Microsoft Windows versions, as well as cross-play between Xbox One and Windows versions. Later updates for the game enabled the ability to modify core rules and adding new game modes, including ones based on ice hockey and basketball.
Rocket League is a sequel to Psyonix's Supersonic Acrobatic Rocket-Powered Battle-Cars, released in 2008 for the PlayStation 3. Battle-Cars received mixed reviews and was not a major success, but gained a loyal fan base. Psyonix continued to support themselves through contract development work for other studios while looking to develop a Battle-Cars sequel. Psyonix began formal development of Rocket League around 2013, refining the gameplay from Battle-Cars to address criticism and fan input. Psyonix also recognized their lack of marketing from Battle-Cars, and engaged in both social media and promotions, including offering the title as a free download for PlayStation Plus members on release, to market the game.
Rocket League has been critically praised, earning a number of industry awards, and saw more than six million sales and at least 18 million unique players a year after its release. Rocket League has also been adopted as an eSport, with professional players participating through ESL and Major League Gaming, along with Psyonix's own Rocket League Championship Series.</div>
<div class="div1" style="margin-top:30px">Gameplay</div>
<div id="AboutTheGameDiv2">
Rocket League's gameplay is largely the same as that of its predecessor Supersonic Acrobatic Rocket-Powered Battle-Cars. Players control a rocket-powered car and use it to hit a ball that is much larger than the cars towards the other team's goal area to score points, in a way that resembles a soccer game, with elements reminiscent of a demolition derby.[1][2] Players' cars have the ability to jump to hit the ball while in mid-air. The players can also pick up a speed boost by passing their cars over marked spaces on the field, enabling them to quickly cross the field, use the added momentum to hit the ball, or ram into another player's car to destroy it; in the latter case, the destroyed car respawns moments later. A player may also utilize boost when in the air to propel themselves forward in flight, allowing players to hit the ball in the air. Players can also perform quick dodges, causing their car to do a short jump and spin in a given direction, which can be used to nudge the ball or gain positioning advantage over the other team.
Matches are typically five minutes long, with a sudden death overtime if the game is tied at that point. Matches can be played from between one-on-one up to four-on-four players, as well as casual and ranked.[6] Rocket League also includes a competitive ranked online mode, where players compete in various tiered ranks within game seasons, with victories or losses raising or lowering a player's rank, respectively. The game includes a single-player "season" mode, with the player competing with computer-controlled players. An update in December 2016 introduced "Custom Training" sequences that can be created by players and shared with others on the same platform; players are able to specify the ball's path and the presence and skill of opponents on the field as to practice specific shots-on-goal over and over.
A few months after it was released, Psyonix released an update that adds game modes known as "mutators", modifying some aspects of gameplay, such as increased or decreased gravity, ball size, ball speed and bounciness.[9] For the 2015 holiday season, another update replaced mutator matches with an ice hockey-inspired mode (called "Snow Day"), played on an ice rink and the ball replaced with a hockey puck with different physics. Positive reception to the ice hockey mode led to it being extended for a few weeks after the holiday season. Snow Day was permanently added to the mutator settings for private matches and exhibition games on February 10, 2016. "Hoops", a game mode based on basketball, was added on April 26, 2016. A separate "Rumble" mode, which incorporates unusual power-ups, such as the ability to freeze the ball in place or cause a single opponent to have difficulty controlling their car, was added on September 8, 2016, as well as including with the update the new "Crates" system. An update in December 2016, known as "Starbase ARC" (based on Psyonix' mobile game ARC Squadron)[18] added support for custom arenas for Windows players supported through Steam Workshop, along with other new content.
A new game mode, Dropshot, was added in a March 2017 update. It takes place on an arena without any goals and a field made of hexagonal tiles, and uses a ball that becomes electrified after successful strikes or passes. Players use the ball to mark tiles on the opposing's side of the field while the ball is electrified; marked tiles are then removed from the field when the electrified ball hits them, or marked tiles in contact with it, creating a goal for the team. Once a team scores, the floor resets to normal
</div>
<div style="height:50px"></div>
</div>
</center>
</asp:Content>

